### ISSUE TITLE
Fix `hoek` security vulnerability

### ISSUE THREAD

**Issue by james-nash** [buildit/gravity-ui-sass#115]
Github is reporting a vulnerability in one of our (indirect) dependencies:

![image](https://user-images.githubusercontent.com/16718916/39537565-e795c45e-4e31-11e8-97fd-a049ce564043.png)

We should update our dependencies to resolve this as soon as possible (assuming of course, that they themselves have updated to a newer version of `hoek`).

**Comment by ThePeach** [comment]
so apparently this is something that @buildit/gravy has, and it's due to https://github.com/sass/node-sass/issues/2355 which won't be fixed until v5 is out.

**Comment by ThePeach** [comment]
related gravy issue is: https://github.com/buildit/gravy/issues/16
