### ISSUE TITLE
Simplify and clarify icon usage

### ISSUE THREAD

**Issue by james-nash** [buildit/gravity-ui-sass#120]
- Should logos for 3rd party services be part of Gravity or not?
- How do we better support and document where and how icons can be used by projects consuming Gravity

References #93

**Comment by wipro-zara** [comment]
Does third party services include the likes of facebook, twitter, instagram etc?

**Comment by james-nash** [comment]
@zara-n This is probably the latest reply _ever_, but to answer your question from last May: Yes, services like FB, Twitter, Insta, etc. is exactly what I mean by "3rd party services". :-)

**Comment by james-nash** [comment]
Looking at this now, I'd say this issue is essentially a dupe of #93, so I'm going to close this.
