### ISSUE TITLE
Job List organism should be a molecule

### ISSUE THREAD

**Issue by danbull** [buildit/gravity-ui-sass#140]

**Comment by danbull** [comment]
@ThePeach I remember you asked me to add this as an issue but I was about to implement it and I disagree. The Job list is composed of a heading and a Job Card repeated multiple times - that sounds like an organism to me?

**Comment by c1rrus** [comment]
@danbull I agree with you. I think organism is an appropriate category for the "job list". Will go ahead a close this issue.
