### ISSUE TITLE
Travis NPM deployment doesn't work

### ISSUE THREAD

**Issue by james-nash** [buildit/gravity-ui-sass#157]
Normally, having a commit on our master branch tagged with `vX.Y.X`, triggers both:
* a styleguide deployment to http://style.buildit.digital/
* a NPM package deployment to https://www.npmjs.com/package/@buildit/gravity-ui-sass

On the most recent `v0.11.0` release, the former worked fine but the latter did not happen.

The offending build log is here: https://travis-ci.org/buildit/gravity-ui-sass/builds/446548115
(I tried re-running that build, but the result was the same)

The build logs show [this error](https://travis-ci.org/buildit/gravity-ui-sass/builds/446548115#L676):
```
Skipping a deployment with the script provider because this branch is not permitted: v0.11.0
```

No idea why this used to work but now fails. Our `.travis.yml` file hasn't been touched in months and this used to work fine.

Can someone please investigate and fix?

**Comment by james-nash** [comment]
I think I may have found the culprit. Saw this warning messagein the most recent release build (which again failed to deploy to NPM):
```
Preparing deploy
NPM version: 6.4.1
Authenticated with email buildit.dev@gmail.com and API key ****************c311
NPM API key format changed recently. If your deployment fails, check your API key in ~/.npmrc.
http://docs.travis-ci.com/user/deployment/npm/
~/.npmrc size: 48
```

Sure enough, later on when it tries to do `npm publish` this happens:
```
npm notice === Tarball Details === 
npm notice name:          @buildit/gravity-ui-sass                
npm notice version:       0.11.1                                  
npm notice package size:  61.8 kB                                 
npm notice unpacked size: 179.9 kB                                
npm notice shasum:        8931ee2e019258ead34d8e729de6036bc1a03572
npm notice integrity:     sha512-myIC6zhvUvS2j[...]iI5eio1oOIwfw==
npm notice total files:   72                                      
npm notice 
npm ERR! publish Failed PUT 401
npm ERR! code EAUTHUNKNOWN
npm ERR! Unable to authenticate, need: Basic, Bearer
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/travis/.npm/_logs/2018-11-28T16_50_34_047Z-debug.log
```

**Comment by james-nash** [comment]
@dm / @booker-macedo (which one should I use? :-P ): I think this might be the same issue we had on the Buildit website. Whenever you next have a spare moment, would you mind taking a look?

**Comment by dm** [comment]
This is fixed, BTW! 👍
